# Generated by Django 6.1 on 2026-08-21 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(help_text='1 a 14')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['promocion', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(db_index=True, max_length=8, unique=True)),
                ('apellidos_nombres', models.CharField(max_length=200)),
                ('grado', models.CharField(max_length=100)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('id_biometrico', models.CharField(help_text='ID de usuario tal como quedó registrado en el iClock880. Se recomienda que sea igual al DNI; si el equipo no lo permite, se usa un código propio y este campo mapea a ese docente.', max_length=24, unique=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['apellidos_nombres'],
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HoraPedagogica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bloque', models.PositiveSmallIntegerField(unique=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo', models.CharField(choices=[('CLASE', 'Clase'), ('RECESO', 'Receso'), ('ALMUERZO', 'Almuerzo')], default='CLASE', max_length=10)),
            ],
            options={
                'verbose_name': 'Hora Pedagógica',
                'verbose_name_plural': 'Grilla de Horas Pedagógicas',
                'ordering': ['numero_bloque'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_periodo', models.PositiveSmallIntegerField(help_text='1 a 6')),
                ('nombre', models.CharField(blank=True, help_text='Ej. "III Periodo"', max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('EN_CURSO', 'En curso'), ('CERRADO', 'Cerrado')], default='PLANIFICADO', max_length=15)),
            ],
            options={
                'verbose_name': 'Período Académico',
                'verbose_name_plural': 'Períodos Académicos',
                'ordering': ['promocion', 'numero_periodo'],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. "JUSTICIEROS 2025-I"', max_length=100, unique=True)),
                ('anio_ingreso', models.PositiveIntegerField()),
                ('fecha_inicio_formacion', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CULMINADA', 'Culminada')], default='ACTIVA', max_length=10)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-anio_ingreso', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_pedagogicas_totales', models.PositiveSmallIntegerField(help_text='Cantidad total de horas pedagógicas por sesión (ej. 3, 4, 6).')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='asistencia.aula')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='asistencia.docente')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['aula', 'oferta_curso'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('especialidad', models.ForeignKey(blank=True, help_text='Vacío si el curso es común a todas las especialidades.', null=True, on_delete=django.db.models.deletion.PROTECT, to='asistencia.especialidad')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='aula',
            name='especialidad',
            field=models.ForeignKey(blank=True, help_text='Se asigna a partir del III período académico.', null=True, on_delete=django.db.models.deletion.PROTECT, to='asistencia.especialidad'),
        ),
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='asistencia.asignacion')),
                ('hora_pedagogica_fin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bloques_fin', to='asistencia.horapedagogica')),
                ('hora_pedagogica_inicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bloques_inicio', to='asistencia.horapedagogica')),
            ],
            options={
                'verbose_name': 'Bloque de Horario',
                'verbose_name_plural': 'Bloques de Horario',
                'ordering': ['dia_semana', 'hora_pedagogica_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MarcacionBiometrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_biometrico', models.CharField(db_index=True, max_length=24)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('DESCONOCIDO', 'Desconocido')], default='DESCONOCIDO', max_length=15)),
                ('origen_dispositivo', models.CharField(default='iClock880', max_length=50)),
                ('importado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marcación Biométrica',
                'verbose_name_plural': 'Marcaciones Biométricas',
                'ordering': ['-timestamp'],
                'unique_together': {('id_biometrico', 'timestamp', 'origen_dispositivo')},
            },
        ),
        migrations.CreateModel(
            name='OfertaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas', to='asistencia.curso')),
                ('periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_curso', to='asistencia.periodoacademico')),
            ],
            options={
                'verbose_name': 'Oferta de Curso',
                'verbose_name_plural': 'Ofertas de Curso',
                'ordering': ['periodo_academico', 'curso'],
                'unique_together': {('periodo_academico', 'curso')},
            },
        ),
        migrations.AddField(
            model_name='asignacion',
            name='oferta_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='asistencia.ofertacurso'),
        ),
        migrations.AddField(
            model_name='periodoacademico',
            name='promocion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='asistencia.promocion'),
        ),
        migrations.AddField(
            model_name='aula',
            name='promocion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='asistencia.promocion'),
        ),
        migrations.CreateModel(
            name='AsistenciaResuelta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('estado', models.CharField(choices=[('PUNTUAL', 'Puntual'), ('TARDANZA', 'Tardanza'), ('FALTA', 'Falta'), ('SOLO_ENTRADA', 'Solo marcó entrada'), ('SOLO_SALIDA', 'Solo marcó salida'), ('NO_PROGRAMADO', 'No programado'), ('AMBIGUO', 'Ambiguo (revisar)')], max_length=15)),
                ('minutos_tardanza', models.PositiveIntegerField(default=0)),
                ('horas_efectivas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('requiere_revision', models.BooleanField(default=False)),
                ('asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='asistencia.asignacion')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='asistencia.docente')),
                ('marcacion_entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_como_entrada', to='asistencia.marcacionbiometrica')),
                ('marcacion_salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_como_salida', to='asistencia.marcacionbiometrica')),
            ],
            options={
                'verbose_name': 'Asistencia Resuelta',
                'verbose_name_plural': 'Asistencias Resueltas',
                'ordering': ['-fecha', 'docente'],
                'unique_together': {('docente', 'asignacion', 'fecha')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='asignacion',
            unique_together={('aula', 'oferta_curso')},
        ),
        migrations.AlterUniqueTogether(
            name='periodoacademico',
            unique_together={('promocion', 'numero_periodo')},
        ),
        migrations.AlterUniqueTogether(
            name='aula',
            unique_together={('promocion', 'numero')},
        ),
    ]
