# Generated by Django 6.1 on 2026-08-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_seed_horas_pedagogicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='dni',
            field=models.CharField(blank=True, db_index=True, help_text='Opcional al crear el docente; se puede regularizar después. No es necesario para que el control de asistencia funcione (eso usa el ID Biometrico).', max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='grado',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
