# Generated by Django 6.1 on 2026-08-21 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alter_docente_dni_alter_docente_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ['promocion__nombre', 'numero'], 'verbose_name': 'Aula', 'verbose_name_plural': 'Aulas'},
        ),
        migrations.AlterModelOptions(
            name='ofertacurso',
            options={'ordering': ['periodo_academico__promocion__nombre', 'periodo_academico__numero_periodo', 'curso__nombre'], 'verbose_name': 'Oferta de Curso', 'verbose_name_plural': 'Ofertas de Curso'},
        ),
    ]
