# Generated by Django 6.1 on 2026-08-22 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_alter_aula_options_alter_ofertacurso_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='horas_pedagogicas_totales',
        ),
        migrations.RemoveField(
            model_name='bloquehorario',
            name='asignacion',
        ),
        migrations.AddField(
            model_name='bloquehorario',
            name='oferta_curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='asistencia.ofertacurso'),
            preserve_default=False,
        ),
    ]
