# Generated by Django 6.1 on 2026-08-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_grupos_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciaresuelta',
            name='horas_pedagogicas_descontadas',
            field=models.PositiveSmallIntegerField(default=0, help_text='Horas pedagógicas (45 min c/u) que ya habían transcurrido por completo al momento de marcar entrada, cuando la tardanza es de 15 minutos o más. Se descuentan automáticamente, sin revisión manual.'),
        ),
        migrations.AddField(
            model_name='asistenciaresuelta',
            name='salida_anticipada',
            field=models.BooleanField(default=False, help_text='El docente marcó salida antes de la hora programada de fin. No se descuenta solo — queda para que jefatura decida.'),
        ),
    ]
