# Generated by Django 6.1 on 2026-08-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0007_asistenciaresuelta_horas_pedagogicas_descontadas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('FERIADO_NACIONAL', 'Feriado nacional'), ('SUSPENSION_SUPERIOR', 'Suspensión por disposición superior')], default='FERIADO_NACIONAL', max_length=25)),
            ],
            options={
                'verbose_name': 'Feriado / Suspensión',
                'verbose_name_plural': 'Feriados y Suspensiones',
                'ordering': ['-fecha'],
            },
        ),
    ]
