# Generated by Django 6.1 on 2026-08-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0008_feriado'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodoacademico',
            name='usa_sabado',
            field=models.BooleanField(default=True, help_text='Si este período dicta clases los sábados. Al desactivarlo, el sábado deja de aparecer en el horario y no se puede programar cursos ese día.'),
        ),
    ]
