# Generated by Django 6.1 on 2026-08-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0009_periodoacademico_usa_sabado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaresuelta',
            name='estado',
            field=models.CharField(choices=[('PUNTUAL', 'Puntual'), ('TARDANZA', 'Tardanza'), ('FALTA', 'Falta'), ('SOLO_ENTRADA', 'Solo marcó entrada'), ('SOLO_SALIDA', 'Solo marcó salida'), ('NO_PROGRAMADO', 'No programado'), ('AMBIGUO', 'Ambiguo (revisar)'), ('RECUPERACION', 'Recuperación nocturna')], max_length=15),
        ),
    ]
