# Generated by Django 6.1 on 2026-09-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0010_alter_asistenciaresuelta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciaresuelta',
            name='corregido_manualmente',
            field=models.BooleanField(default=False, help_text='Jefatura ajustó el estado a mano desde el reporte. Mientras esté activo, cerrar_dia ya no recalcula este registro automáticamente (así una resincronización o un cierre tardío no borra la corrección).'),
        ),
    ]
