# Generated by Django 6.1 on 2026-09-22 14:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0012_registroactividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. 2026-II, Semestre I 2026, etc.', max_length=100, unique=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
                'ordering': ['-fecha_inicio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=150)),
                ('nombres', models.CharField(max_length=150)),
                ('dni', models.CharField(blank=True, max_length=15, verbose_name='DNI')),
                ('cip', models.CharField(blank=True, help_text='Opcional — solo aplica a personal PNP.', max_length=15, verbose_name='CIP')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='Telf. celular')),
                ('grado', models.CharField(choices=[('CIVIL', 'Civil'), ('GENERAL', 'General'), ('CORONEL', 'Coronel'), ('COMANDANTE', 'Comandante'), ('MAYOR', 'Mayor'), ('CAPITAN', 'Capitán'), ('TENIENTE', 'Teniente'), ('ALFEREZ', 'Alférez'), ('SO_SUPERIOR', 'Suboficial Superior'), ('SO_BRIGADIER', 'Suboficial Brigadier'), ('SOT1', 'Suboficial Técnico de 1ra'), ('SOT2', 'Suboficial Técnico de 2da'), ('SOT3', 'Suboficial Técnico de 3ra'), ('SO1', 'Suboficial de 1ra'), ('SO2', 'Suboficial de 2da'), ('SO3', 'Suboficial de 3ra')], default='CIVIL', max_length=15)),
                ('procedencia', models.CharField(choices=[('PNP', 'PNP'), ('FFAA', 'Fuerzas Armadas'), ('CIVIL', 'Civil'), ('EXTRANJERO', 'Extranjero')], default='CIVIL', max_length=12)),
                ('postula_a_otro_curso_misma_convocatoria', models.BooleanField(default=False, help_text='Márcalo si esta misma persona tiene otro registro de postulante en esta convocatoria (para otra unidad didáctica) — sirve para el listado por curso que se hará más adelante.', verbose_name='También postula a otro curso en esta misma convocatoria')),
                ('fecha_evaluacion', models.DateField(blank=True, null=True)),
                ('tiene_titulo_profesional', models.BooleanField(default=False, verbose_name='Título Profesional Universitario / en Adm. y CC. Policiales')),
                ('tiene_titulo_profesional_tecnico', models.BooleanField(default=False, verbose_name='Título Profesional Técnico en ciencias policiales (solo Anexo 13)')),
                ('tiene_maestria', models.BooleanField(default=False, verbose_name='Grado académico de Maestro')),
                ('tiene_doctorado', models.BooleanField(default=False, verbose_name='Grado académico de Doctor')),
                ('tiene_segunda_especialidad', models.BooleanField(default=False, verbose_name='Segunda especialidad o título de especialista')),
                ('diplomados_120h', models.PositiveSmallIntegerField(default=0, verbose_name='Diplomados afines ≥120h (1.0 c/u, tope 2)')),
                ('programas_16_96h_afines', models.PositiveSmallIntegerField(default=0, verbose_name='Programas afines 16-96h (0.5 c/u, tope 2)')),
                ('ponente_eventos', models.PositiveSmallIntegerField(default=0, verbose_name='Ponente en eventos académicos (0.5 c/u, tope 1)')),
                ('asistente_eventos', models.PositiveSmallIntegerField(default=0, verbose_name='Asistente a eventos académicos (0.5 c/u, tope 1)')),
                ('investigaciones', models.PositiveSmallIntegerField(default=0, verbose_name='Investigaciones en la especialidad (1.0 c/u, tope 1)')),
                ('publicaciones', models.PositiveSmallIntegerField(default=0, verbose_name='Textos y/o libros publicados (1.0 c/u, tope 1)')),
                ('programas_96h_otros', models.PositiveSmallIntegerField(default=0, verbose_name='Programas ≥96h (1.0 c/u, tope 2)')),
                ('programas_16_96h_otros', models.PositiveSmallIntegerField(default=0, verbose_name='Programas 16-96h (0.5 c/u, tope 2)')),
                ('cursos_ofimatica_24h', models.PositiveSmallIntegerField(default=0, verbose_name='Cursos de ofimática ≥24h (0.5 c/u, tope 2)')),
                ('pregrado_ciclos', models.PositiveSmallIntegerField(default=0, verbose_name='Docencia nivel pregrado, en ciclos (0.5 c/ciclo)')),
                ('maestria_cursos', models.PositiveSmallIntegerField(default=0, verbose_name='Docencia posgrado Maestría, en cursos (0.5 c/curso, tope 1)')),
                ('experiencia_profesional_anios', models.PositiveSmallIntegerField(default=0, verbose_name='Ejercicio profesional no docente, en años (1.0 c/año, tope 6)')),
                ('cd_planificacion', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Planificación y evaluación de sesiones')),
                ('cd_dominio_pedagogico', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Dominio pedagógico')),
                ('cd_dominio_tecnico', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Dominio técnico')),
                ('cd_comunicacion', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Comunicación efectiva')),
                ('cd_recursos_tecnologicos', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Uso de recursos tecnológicos')),
                ('ep_proceso_ensenanza', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Proceso de enseñanza-aprendizaje')),
                ('ep_desarrollo_institucional', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Desarrollo institucional')),
                ('ep_especialidad_experiencia', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Especialidad y experiencia')),
                ('ep_investigacion_innovacion', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Investigación e innovación')),
                ('ep_personalidad', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Personalidad')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postulantes', to='asistencia.convocatoria')),
                ('docente', models.ForeignKey(blank=True, help_text='Se detecta solo por DNI al guardar, si ya existe un Docente con ese mismo DNI. También puedes seleccionarlo a mano si hace falta — nunca se vincula por nombre parecido.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulaciones', to='asistencia.docente')),
                ('unidad_didactica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postulantes', to='asistencia.curso', verbose_name='Unidad didáctica / curso al que postula')),
            ],
            options={
                'verbose_name': 'Postulante (calificación docente)',
                'verbose_name_plural': 'Postulantes (calificación docente)',
                'ordering': ['convocatoria', 'unidad_didactica', 'apellidos', 'nombres'],
            },
        ),
    ]
