# Generated by Django 6.1 on 2026-09-21 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0012_registroactividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos_nombres', models.CharField(max_length=200)),
                ('dni_cip', models.CharField(blank=True, max_length=20, verbose_name='DNI / CIP')),
                ('grado', models.CharField(blank=True, help_text="Grado policial o 'Civil'", max_length=100)),
                ('procedencia', models.CharField(choices=[('PNP', 'PNP'), ('FFAA', 'Fuerzas Armadas'), ('CIVIL', 'Civil'), ('EXTRANJERO', 'Extranjero')], default='CIVIL', max_length=12)),
                ('escuela', models.CharField(choices=[('EESTP', 'EESTP PNP'), ('EO', 'Escuela de Oficiales PNP'), ('ESCFOCON', 'ESCFOCON PNP'), ('ESCPOGRA', 'ESCPOGRA PNP')], default='EESTP', max_length=10)),
                ('unidad_didactica', models.CharField(max_length=200, verbose_name='Unidad didáctica / curso al que postula')),
                ('convocatoria', models.CharField(help_text='Ej. 2026-II, Semestre I 2026, etc.', max_length=100)),
                ('fecha_evaluacion', models.DateField(blank=True, null=True)),
                ('tabla_curricular', models.CharField(choices=[('ANEXO_10', 'Anexo 10 — Concurso público general (civiles / EO-ESCFOCON-ESCPOGRA)'), ('ANEXO_13', 'Anexo 13 — Ingreso de Suboficiales como docente (EESTP)')], default='ANEXO_10', help_text='Según el origen del postulante, define cómo se puntúan grados y títulos (Anexo 10 vs Anexo 13).', max_length=10)),
                ('tiene_titulo_profesional', models.BooleanField(default=False, verbose_name='Título Profesional Universitario / en Adm. y CC. Policiales')),
                ('tiene_titulo_profesional_tecnico', models.BooleanField(default=False, verbose_name='Título Profesional Técnico en ciencias policiales (solo Anexo 13)')),
                ('tiene_maestria', models.BooleanField(default=False, verbose_name='Grado académico de Maestro')),
                ('tiene_doctorado', models.BooleanField(default=False, verbose_name='Grado académico de Doctor')),
                ('tiene_segunda_especialidad', models.BooleanField(default=False, verbose_name='Segunda especialidad o título de especialista')),
                ('diplomados_120h', models.PositiveSmallIntegerField(default=0, verbose_name='Diplomados afines ≥120h (1.0 c/u, tope 2)')),
                ('programas_16_96h_afines', models.PositiveSmallIntegerField(default=0, verbose_name='Programas afines 16-96h (0.5 c/u, tope 2)')),
                ('ponente_eventos', models.PositiveSmallIntegerField(default=0, verbose_name='Ponente en eventos académicos (0.5 c/u, tope 1)')),
                ('asistente_eventos', models.PositiveSmallIntegerField(default=0, verbose_name='Asistente a eventos académicos (0.5 c/u, tope 1)')),
                ('investigaciones', models.PositiveSmallIntegerField(default=0, verbose_name='Investigaciones en la especialidad (1.0 c/u, tope 1)')),
                ('publicaciones', models.PositiveSmallIntegerField(default=0, verbose_name='Textos y/o libros publicados (1.0 c/u, tope 1)')),
                ('programas_96h_otros', models.PositiveSmallIntegerField(default=0, verbose_name='Programas ≥96h (1.0 c/u, tope 2)')),
                ('programas_16_96h_otros', models.PositiveSmallIntegerField(default=0, verbose_name='Programas 16-96h (0.5 c/u, tope 2)')),
                ('cursos_ofimatica_24h', models.PositiveSmallIntegerField(default=0, verbose_name='Cursos de ofimática ≥24h (0.5 c/u, tope 2)')),
                ('pregrado_ciclos', models.PositiveSmallIntegerField(default=0, verbose_name='Docencia nivel pregrado, en ciclos (0.5 c/ciclo)')),
                ('maestria_cursos', models.PositiveSmallIntegerField(default=0, verbose_name='Docencia posgrado Maestría, en cursos (0.5 c/curso, tope 1)')),
                ('doctorado_cursos', models.PositiveSmallIntegerField(default=0, verbose_name='Docencia posgrado Doctorado, en cursos (0.5 c/curso, tope 1; solo Anexo 10)')),
                ('experiencia_profesional_anios', models.PositiveSmallIntegerField(default=0, verbose_name='Ejercicio profesional no docente, en años (1.0 c/año, tope 6)')),
                ('cd_planificacion', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Planificación y evaluación de sesiones')),
                ('cd_dominio_pedagogico', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Dominio pedagógico')),
                ('cd_dominio_tecnico', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Dominio técnico')),
                ('cd_comunicacion', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Comunicación efectiva')),
                ('cd_recursos_tecnologicos', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Uso de recursos tecnológicos')),
                ('ep_proceso_ensenanza', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Proceso de enseñanza-aprendizaje')),
                ('ep_desarrollo_institucional', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Desarrollo institucional')),
                ('ep_especialidad_experiencia', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Especialidad y experiencia')),
                ('ep_investigacion_innovacion', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Investigación e innovación')),
                ('ep_personalidad', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Personalidad')),
            ],
            options={
                'verbose_name': 'Postulante (calificación docente)',
                'verbose_name_plural': 'Postulantes (calificación docente)',
                'ordering': ['convocatoria', 'unidad_didactica', 'apellidos_nombres'],
            },
        ),
    ]
