# Generated by Django 6.1 on 2026-09-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0013_convocatoria_unidaddidacticaconvocatoria_postulante'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioPuntaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(help_text='Identificador técnico — debe coincidir con el campo del postulante que puntúa. No cambiarlo.', unique=True)),
                ('etiqueta', models.CharField(max_length=200)),
                ('bloque', models.PositiveSmallIntegerField(choices=[(1, '1. Grados académicos y títulos profesionales'), (2, '2. Actualizaciones y capacitaciones afines'), (3, '3. Participación en eventos científicos e investigación'), (4, '4. Otros programas de formación continua'), (5, '5. Experiencia docente universitaria'), (6, '6. Experiencia profesional')])),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('puntaje_por_unidad', models.DecimalField(decimal_places=2, help_text='Para casillas (sí/no) es el puntaje que se da una sola vez. Para conteos, el puntaje c/u.', max_digits=4, verbose_name='Puntaje por unidad')),
                ('tope', models.DecimalField(decimal_places=2, help_text='Puntaje máximo que puede aportar este criterio, sin importar cuántas unidades se registren.', max_digits=4, verbose_name='Puntaje máximo (tope)')),
            ],
            options={
                'verbose_name': 'Criterio de puntaje',
                'verbose_name_plural': 'Criterios de puntaje (escala de calificación)',
                'ordering': ['bloque', 'orden'],
            },
        ),
        migrations.AlterField(
            model_name='postulante',
            name='grado',
            field=models.CharField(choices=[('GENERAL', 'General'), ('CORONEL', 'Coronel'), ('COMANDANTE', 'Comandante'), ('MAYOR', 'Mayor'), ('CAPITAN', 'Capitán'), ('TENIENTE', 'Teniente'), ('ALFEREZ', 'Alférez'), ('SO_SUPERIOR', 'Suboficial Superior'), ('SO_BRIGADIER', 'Suboficial Brigadier'), ('SOT1', 'Suboficial Técnico de 1ra'), ('SOT2', 'Suboficial Técnico de 2da'), ('SOT3', 'Suboficial Técnico de 3ra'), ('SO1', 'Suboficial de 1ra'), ('SO2', 'Suboficial de 2da'), ('SO3', 'Suboficial de 3ra'), ('CIVIL', 'Civil (sin título indicado)'), ('TECNICO', 'Técnico'), ('BACHILLER', 'Bachiller'), ('LICENCIADO', 'Licenciado'), ('INGENIERO', 'Ingeniero'), ('ABOGADO', 'Abogado'), ('MAGISTER', 'Magíster'), ('DOCTOR', 'Doctor'), ('OTRO', 'Otro')], default='CIVIL', max_length=15),
        ),
    ]
