# Generated by Django 6.1 on 2026-09-21 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0013_postulante'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='celular',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telf. celular'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='docente',
            field=models.ForeignKey(blank=True, help_text='Si esta persona YA existe como Docente en el sistema (por ejemplo, sigue postulando a otro curso), selecciónala aquí para no crear un duplicado. Búscala por DNI o nombre completo exacto — no la vincules por coincidencia parcial de nombre.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulaciones', to='asistencia.docente'),
        ),
    ]
