# Generated by Django 6.1 on 2026-09-22 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0015_seed_criterios_puntaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='asistente_eventos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Asistente a eventos académicos (0.5 c/u, tope 1)'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='cursos_ofimatica_24h',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cursos de ofimática ≥24h (0.5 c/u, tope 2)'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='diplomados_120h',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Diplomados afines ≥120h (1.0 c/u, tope 2)'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='experiencia_profesional_anios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ejercicio profesional no docente, en años (1.0 c/año, tope 6)'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='investigaciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Investigaciones en la especialidad (1.0 c/u, tope 1)'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='maestria_cursos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Docencia posgrado Maestría, en cursos (0.5 c/curso, tope 1)'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='ponente_eventos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ponente en eventos académicos (0.5 c/u, tope 1)'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='pregrado_ciclos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Docencia nivel pregrado, en ciclos (0.5 c/ciclo)'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='programas_16_96h_afines',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Programas afines 16-96h (0.5 c/u, tope 2)'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='programas_16_96h_otros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Programas 16-96h (0.5 c/u, tope 2)'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='programas_96h_otros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Programas ≥96h (1.0 c/u, tope 2)'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='publicaciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Textos y/o libros publicados (1.0 c/u, tope 1)'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='tiene_titulo_profesional',
            field=models.BooleanField(default=False, verbose_name='Título Profesional (Universitario si es Civil/Extranjero — Anexo 10; en Administración y CC. Policiales si es PNP/FFAA — Anexo 13)'),
        ),
    ]
