# Generated by Django 6.1 on 2026-09-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0017_ajusta_criterios_bloque1_titulo_universitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=15, unique=True, verbose_name='DNI')),
                ('apellidos', models.CharField(max_length=150)),
                ('nombres', models.CharField(max_length=150)),
                ('cip', models.CharField(blank=True, help_text='Opcional — solo aplica a personal PNP.', max_length=15, verbose_name='CIP')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='Telf. celular')),
                ('procedencia', models.CharField(blank=True, choices=[('PNP', 'PNP'), ('FFAA', 'Fuerzas Armadas'), ('CIVIL', 'Civil'), ('EXTRANJERO', 'Extranjero')], max_length=12)),
                ('grado', models.CharField(blank=True, choices=[('GENERAL', 'General'), ('CORONEL', 'Coronel'), ('COMANDANTE', 'Comandante'), ('MAYOR', 'Mayor'), ('CAPITAN', 'Capitán'), ('TENIENTE', 'Teniente'), ('ALFEREZ', 'Alférez'), ('SO_SUPERIOR', 'Suboficial Superior'), ('SO_BRIGADIER', 'Suboficial Brigadier'), ('SOT1', 'Suboficial Técnico de 1ra'), ('SOT2', 'Suboficial Técnico de 2da'), ('SOT3', 'Suboficial Técnico de 3ra'), ('SO1', 'Suboficial de 1ra'), ('SO2', 'Suboficial de 2da'), ('SO3', 'Suboficial de 3ra'), ('CIVIL', 'Civil (sin título indicado)'), ('TECNICO', 'Técnico'), ('BACHILLER', 'Bachiller'), ('LICENCIADO', 'Licenciado'), ('INGENIERO', 'Ingeniero'), ('ABOGADO', 'Abogado'), ('MAGISTER', 'Magíster'), ('DOCTOR', 'Doctor'), ('OTRO', 'Otro')], max_length=15)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Persona (referencia de búsqueda por DNI)',
                'verbose_name_plural': 'Personas (referencia de búsqueda por DNI)',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.AddField(
            model_name='postulante',
            name='tipo_titulo_profesional',
            field=models.CharField(blank=True, choices=[('UNIVERSITARIO', 'Universitario (Anexo 10 — 4 pts)'), ('POLICIAL', 'Administración y CC. Policiales (Anexo 13 — 5 pts)')], default='UNIVERSITARIO', help_text='Solo si marcaste "Título Profesional": elige con qué puntaje se califica — Universitario (Anexo 10) o en Administración y CC. Policiales (Anexo 13).', max_length=15, verbose_name='Tipo de título profesional'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='tiene_titulo_profesional',
            field=models.BooleanField(default=False, verbose_name='Título Profesional'),
        ),
    ]
