# Generated by Django 6.1 on 2026-09-23 17:51, reordenado a mano para
# copiar los datos existentes antes de borrar los campos viejos.

from django.db import migrations, models


def copiar_datos(apps, schema_editor):
    Postulante = apps.get_model("asistencia", "Postulante")
    for p in Postulante.objects.all():
        cambio = False
        if p.tiene_titulo_profesional_tecnico:
            p.tiene_titulo_tecnico_o_civil = True
            cambio = True
        if p.tiene_maestria or p.tiene_doctorado:
            p.tiene_maestria_o_doctorado = True
            cambio = True
        if cambio:
            p.save(update_fields=["tiene_titulo_tecnico_o_civil", "tiene_maestria_o_doctorado"])


def revertir_datos(apps, schema_editor):
    # No hay forma de saber si un tiene_maestria_o_doctorado marcado era
    # maestría o doctorado — al revertir queda todo como maestría.
    Postulante = apps.get_model("asistencia", "Postulante")
    for p in Postulante.objects.all():
        cambio = False
        if p.tiene_titulo_tecnico_o_civil:
            p.tiene_titulo_profesional_tecnico = True
            cambio = True
        if p.tiene_maestria_o_doctorado:
            p.tiene_maestria = True
            cambio = True
        if cambio:
            p.save(update_fields=["tiene_titulo_profesional_tecnico", "tiene_maestria"])


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0018_persona_postulante_tipo_titulo_profesional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='observaciones_entrevista',
            field=models.TextField(blank=True, verbose_name='Observaciones de la Entrevista Personal'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='tiene_maestria_o_doctorado',
            field=models.BooleanField(default=False, verbose_name='Grado académico de Maestro/Doctor'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='tiene_titulo_tecnico_o_civil',
            field=models.BooleanField(default=False, verbose_name='Título profesional Técnico en ciencias policiales / profesional civil'),
        ),
        migrations.RunPython(copiar_datos, revertir_datos),
        migrations.RemoveField(
            model_name='postulante',
            name='tiene_doctorado',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='tiene_maestria',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='tiene_titulo_profesional_tecnico',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='tipo_titulo_profesional',
        ),
        migrations.AlterField(
            model_name='postulante',
            name='tiene_segunda_especialidad',
            field=models.BooleanField(default=False, verbose_name='Segunda Especialidad o Título de Especialista de acuerdo a la naturaleza de la UD'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='tiene_titulo_profesional',
            field=models.BooleanField(default=False, verbose_name='Título Profesional en Administración y Ciencias Policiales'),
        ),
    ]
