# Generated by Django 6.1 on 2026-09-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0020_actualiza_criterios_bloque1_hoja_oficial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='grado',
            field=models.CharField(blank=True, choices=[('GENERAL', 'Gral.'), ('CORONEL', 'Cnel.'), ('COMANDANTE', 'Cmdt.'), ('MAYOR', 'My.'), ('CAPITAN', 'Cap.'), ('TENIENTE', 'Tte.'), ('ALFEREZ', 'Alf.'), ('SO_SUPERIOR', 'SOS'), ('SO_BRIGADIER', 'SOB'), ('SOT1', 'SOT1'), ('SOT2', 'SOT2'), ('SOT3', 'SOT3'), ('SO1', 'S1'), ('SO2', 'S2'), ('SO3', 'S3'), ('CIVIL', 'Civil'), ('TECNICO', 'Técnico'), ('BACHILLER', 'Bach.'), ('LICENCIADO', 'Lic.'), ('INGENIERO', 'Ing.'), ('ABOGADO', 'Abg.'), ('MAGISTER', 'Mg.'), ('DOCTOR', 'Dr.'), ('OTRO', 'Otro')], max_length=15),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='grado',
            field=models.CharField(choices=[('GENERAL', 'Gral.'), ('CORONEL', 'Cnel.'), ('COMANDANTE', 'Cmdt.'), ('MAYOR', 'My.'), ('CAPITAN', 'Cap.'), ('TENIENTE', 'Tte.'), ('ALFEREZ', 'Alf.'), ('SO_SUPERIOR', 'SOS'), ('SO_BRIGADIER', 'SOB'), ('SOT1', 'SOT1'), ('SOT2', 'SOT2'), ('SOT3', 'SOT3'), ('SO1', 'S1'), ('SO2', 'S2'), ('SO3', 'S3'), ('CIVIL', 'Civil'), ('TECNICO', 'Técnico'), ('BACHILLER', 'Bach.'), ('LICENCIADO', 'Lic.'), ('INGENIERO', 'Ing.'), ('ABOGADO', 'Abg.'), ('MAGISTER', 'Mg.'), ('DOCTOR', 'Dr.'), ('OTRO', 'Otro')], default='CIVIL', max_length=15),
        ),
    ]
