# Generated by Django 6.1 on 2026-09-25 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0021_abrevia_grados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Cuenta para entrar al Aula Virtual — se crea con la acción "Crear acceso al Aula Virtual" del listado de Docentes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docente', to=settings.AUTH_USER_MODEL),
        ),
    ]
