# Generated by Django 6.1 on 2026-09-25 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0022_docente_usuario_aula_virtual'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('ENLACE', 'Enlace (Drive, YouTube, etc.)'), ('TEXTO', 'Aviso / texto')], default='ENLACE', max_length=10)),
                ('enlace', models.URLField(blank=True, verbose_name='Enlace')),
                ('contenido', models.TextField(blank=True, verbose_name='Contenido / descripción')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='asistencia.asignacion')),
            ],
            options={
                'verbose_name': 'Material de clase',
                'verbose_name_plural': 'Materiales de clase (Aula Virtual)',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
