# Generated by Django 6.1 on 2026-09-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0023_material_clase_aula_virtual'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='password_temporal',
            field=models.BooleanField(default=False, help_text='Su contraseña sigue siendo la que se le puso por defecto (su DNI) — el sistema lo obliga a cambiarla antes de dejarlo ver el Aula Virtual.'),
        ),
    ]
