# Generated by Django 6.1 on 2026-09-25 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0024_docente_password_temporal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, db_index=True, max_length=8, null=True, unique=True)),
                ('apellidos_nombres', models.CharField(max_length=200)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('RETIRADO', 'Retirado')], default='ACTIVO', max_length=10)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('password_temporal', models.BooleanField(default=False, help_text='Su contraseña sigue siendo la que se le puso por defecto (su DNI) — el sistema lo obliga a cambiarla antes de dejarlo ver el Aula Virtual.')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='asistencia.aula')),
                ('usuario', models.OneToOneField(blank=True, help_text='Cuenta para entrar al Aula Virtual — se crea con la acción "Crear acceso al Aula Virtual" del listado de Estudiantes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['apellidos_nombres'],
            },
        ),
    ]
