# Generated by Django 6.1 on 2026-09-25 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0025_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField(verbose_name='Fecha y hora límite de entrega')),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='asistencia.asignacion')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas (Aula Virtual)',
                'ordering': ['-fecha_limite'],
            },
        ),
        migrations.CreateModel(
            name='EntregaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace', models.URLField(verbose_name='Enlace de la entrega')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario (opcional)')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comentario_docente', models.TextField(blank=True)),
                ('fecha_calificacion', models.DateTimeField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='asistencia.estudiante')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='asistencia.tarea')),
            ],
            options={
                'verbose_name': 'Entrega de tarea',
                'verbose_name_plural': 'Entregas de tarea (Aula Virtual)',
                'ordering': ['-fecha_entrega'],
                'unique_together': {('tarea', 'estudiante')},
            },
        ),
    ]
