# Generated by Django 6.1 on 2026-09-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0026_tareas_y_entregas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistenciaresuelta',
            unique_together={('asignacion', 'fecha')},
        ),
    ]
